theme: jekyll-theme-dinky
title: [handover failure detection]
zenodo:
    dataset_url: https://zenodo.org/records/10708763
publication:
    pdf_url: https://arxiv.org/
competition:
    competition_url: https://www.codabench.org/competitions/2150/
github:
  is_project_page: False
