theme: jekyll-theme-dinky
title: [handover failure detection]
zenodo:
    dataset_url: https://zenodo.org/
publication:
    pdf_url: https://arxiv.org/
competition:
    competition_url: https://codalab.lisn.upsaclay.fr/
github:
  is_project_page: False
